# Generated by Django 4.0.2 on 2022-04-11 18:51

from django.db import migrations

def populate_db(apps, schema_editor):
    Todo = apps.get_model('todosAPI', 'Todo')

    todos = ['make website', 'setup django', 'setup AWS', 'publish my website']

    python_download = Todo(task='download python', state='complete')
    python_download.save()

    for todo in todos:
        
        new_todo = Todo(task=todo, state='incomplete')
        new_todo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('todosAPI', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
